import {
  ROLES,
  normalizeRole,
} from "./roles"

export const PERMISSIONS = {
  USUARIOS_GESTIONAR: "usuarios:gestionar",

  CURSOS_VER: "cursos:ver",
  CURSOS_GESTIONAR: "cursos:gestionar",

  ASIGNATURAS_VER: "asignaturas:ver",
  ASIGNATURAS_GESTIONAR: "asignaturas:gestionar",

  ANOTACIONES_VER: "anotaciones:ver",
  ANOTACIONES_CREAR: "anotaciones:crear",
  ANOTACIONES_GESTIONAR: "anotaciones:gestionar",

  CALENDARIO_VER: "calendario:ver",
  CALENDARIO_GESTIONAR: "calendario:gestionar",

  MENSAJES_VER: "mensajes:ver",
  MENSAJES_GESTIONAR: "mensajes:gestionar",

  REUNIONES_VER: "reuniones:ver",
  REUNIONES_GESTIONAR: "reuniones:gestionar",

  PORTAL_VER: "portal:ver",
  PORTAL_GESTIONAR: "portal:gestionar",

  FICHA_ALUMNO_VER: "ficha-alumno:ver",
}

const ALL_PERMISSIONS = Object.values(PERMISSIONS)

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: ALL_PERMISSIONS,

  [ROLES.PROFESOR]: [
    PERMISSIONS.CURSOS_VER,
    PERMISSIONS.ASIGNATURAS_VER,
    PERMISSIONS.ANOTACIONES_VER,
    PERMISSIONS.ANOTACIONES_CREAR,
    PERMISSIONS.CALENDARIO_VER,
    PERMISSIONS.MENSAJES_VER,
  ],

  [ROLES.ALUMNO]: [
    PERMISSIONS.CURSOS_VER,
    PERMISSIONS.ASIGNATURAS_VER,
    PERMISSIONS.CALENDARIO_VER,
    PERMISSIONS.MENSAJES_VER,
    PERMISSIONS.PORTAL_VER,
  ],

  [ROLES.APODERADO]: [
    PERMISSIONS.FICHA_ALUMNO_VER,
    PERMISSIONS.CALENDARIO_VER,
    PERMISSIONS.MENSAJES_VER,
    PERMISSIONS.REUNIONES_VER,
    PERMISSIONS.PORTAL_VER,
  ],

  [ROLES.INSPECTOR]: [
    PERMISSIONS.CURSOS_VER,
    PERMISSIONS.ANOTACIONES_VER,
    PERMISSIONS.ANOTACIONES_CREAR,
    PERMISSIONS.ANOTACIONES_GESTIONAR,
    PERMISSIONS.CALENDARIO_VER,
    PERMISSIONS.CALENDARIO_GESTIONAR,
    PERMISSIONS.MENSAJES_VER,
  ],

  [ROLES.ADMINISTRATIVO]: [
    PERMISSIONS.CURSOS_VER,
    PERMISSIONS.CURSOS_GESTIONAR,

    PERMISSIONS.ASIGNATURAS_VER,
    PERMISSIONS.ASIGNATURAS_GESTIONAR,

    PERMISSIONS.CALENDARIO_VER,
    PERMISSIONS.CALENDARIO_GESTIONAR,

    PERMISSIONS.MENSAJES_VER,
    PERMISSIONS.MENSAJES_GESTIONAR,

    PERMISSIONS.REUNIONES_VER,
    PERMISSIONS.REUNIONES_GESTIONAR,

    PERMISSIONS.PORTAL_VER,
    PERMISSIONS.PORTAL_GESTIONAR,
  ],

  [ROLES.USER]: [],
}

export function hasPermission(role, permission) {
  const normalizedRole = normalizeRole(role)

  return ROLE_PERMISSIONS[normalizedRole]?.includes(permission) || false
}

export function hasAnyPermission(role, permissions = []) {
  return permissions.some((permission) =>
    hasPermission(role, permission)
  )
}